version: '3'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
